#!/usr/bin/env python3
"""Generate font_large.h: 1-bit bitmaps of the digits 0-9 for the main screen.

Usage:
    python3 tools/gen_large_font.py [--font PATH] [--max-height 52] [--out font_large.h]

Requires Pillow. The default font is Liberation Sans Bold (SIL Open Font
License 1.1). Each digit is rendered into a fixed-width cell so the number
does not shift as the speed changes.

Output layout is column-major: for each column, LARGE_FONT_BYTES_PER_COL bytes,
least-significant bit = top row (same orientation as font5x8.h).
"""
import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont

DIGITS = "0123456789"
DEFAULT_FONT = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"
MAX_WIDTH = 128


def measure(font):
    """Return (cell_w, top, bottom) over all digits, with baseline anchoring."""
    tops, bottoms, widths = [], [], []
    for d in DIGITS:
        l, t, r, b = font.getbbox(d, anchor="ls")
        tops.append(t)
        bottoms.append(b)
        widths.append(r - l)
    return max(widths), min(tops), max(bottoms)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default=DEFAULT_FONT)
    ap.add_argument("--max-height", type=int, default=52)
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "..", "font_large.h"))
    args = ap.parse_args()

    # Largest point size whose digits fit the height budget and where two
    # digits (with a small gap) fit across the 128-px display.
    size = 200
    while size > 8:
        font = ImageFont.truetype(args.font, size)
        cw, top, bottom = measure(font)
        if bottom - top <= args.max_height and 2 * cw + 4 <= MAX_WIDTH - 2:
            break
        size -= 1
    else:
        sys.exit("no size fits")

    ch = bottom - top
    bpc = (ch + 7) // 8
    name = os.path.basename(args.font)

    lines = []
    for d in DIGITS:
        im = Image.new("1", (cw, ch), 0)
        dr = ImageDraw.Draw(im)
        dr.fontmode = "1"  # no anti-aliasing: crisp 1-bit pixels
        dr.text((cw / 2, -top), d, font=font, fill=1, anchor="ms")
        px = im.load()
        cols = []
        for x in range(cw):
            for b in range(bpc):
                v = 0
                for bit in range(8):
                    y = b * 8 + bit
                    if y < ch and px[x, y]:
                        v |= 1 << bit
                cols.append(v)
        rows = []
        for i in range(0, len(cols), 14):
            rows.append("    " + ", ".join(f"0x{v:02X}" for v in cols[i:i + 14]) + ",")
        lines.append(f"    /* '{d}' */ {{\n" + "\n".join(rows) + "\n    },")

    out = f"""#ifndef FONT_LARGE_H
#define FONT_LARGE_H

#include <stdint.h>

/*
 * Large digits 0-9 for the main screen, rasterized from {name}
 * ({size} px, no anti-aliasing). Liberation Sans is licensed under the
 * SIL Open Font License 1.1.
 *
 * Generated by tools/gen_large_font.py -- do not edit by hand.
 *
 * Column-major: LARGE_FONT_BYTES_PER_COL bytes per column, LSB = top row.
 */
#define LARGE_FONT_W             {cw}
#define LARGE_FONT_H             {ch}
#define LARGE_FONT_BYTES_PER_COL {bpc}

static const uint8_t font_large_digits[10][LARGE_FONT_W * LARGE_FONT_BYTES_PER_COL] = {{
""" + "\n".join(lines) + """
};

#endif
"""
    with open(args.out, "w") as f:
        f.write(out)
    print(f"{name} @ {size}px -> cell {cw}x{ch}, {10 * cw * bpc} bytes, wrote {os.path.normpath(args.out)}")


if __name__ == "__main__":
    main()
